language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-inception-resnet-v2 .
  - docker run -it -d --rm -p 5000:5000 max-inception-resnet-v2
  - pip install -r requirements-test.txt
before_script:
  - flake8 . --max-line-length=127
  - sleep 90
script:
  - pytest tests/test.py
