language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t max-inception-resnet-v2 .
  - docker run -it -d -p 5000:5000 max-inception-resnet-v2
  - pip install pytest requests flake8 Pillow

before_script:
  - flake8 . --max-line-length=127
  - sleep 60

script:
  - pytest tests/test.py
